export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_CATEGORY_FULFILLED = 'GET_CATEGORY_FULFILLED'
export const GET_CATEGORY_REJECTED = 'GET_CATEGORY_REJECTED'

export const GET_EVENT = 'GET_EVENT'
export const GET_EVENT_FULFILLED = 'GET_EVENT_FULFILLED'
export const GET_EVENT_REJECTED = 'GET_EVENT_REJECTED'

export const GET_EVENT_TODAY = 'GET_EVENT_TODAY'
export const GET_EVENT_TODAY_FULFILLED = 'GET_EVENT_TODAY_FULFILLED'
export const GET_EVENT_TODAY_REJECTED = 'GET_EVENT_TODAY_REJECTED'

export const GET_EVENT_TOMORROW = 'GET_EVENT_TOMORROW'
export const GET_EVENT_TOMORROW_FULFILLED = 'GET_EVENT_TOMORROW_FULFILLED'
export const GET_EVENT_TOMORROW_REJECTED = 'GET_EVENT_TOMORROW_REJECTED'

export const GET_EVENT_DETAIL = 'GET_EVENT_DETAIL'
export const GET_EVENT_DETAIL_FULFILLED = 'GET_EVENT_DETAIL_FULFILLED'
export const GET_EVENT_DETAIL_REJECTED = 'GET_EVENT_DETAIL_REJECTED'

export const GET_EVENT_CATEGORY = 'GET_EVENT_CATEGORY'
export const GET_EVENT_CATEGORY_FULFILLED = 'GET_EVENT_CATEGORY_FULFILLED'
export const GET_EVENT_CATEGORY_REJECTED = 'GET_EVENT_CATEGORY_REJECTED'

export const GET_ORDERPENDING = 'GET_ORDERPENDING'
export const GET_ORDERPENDING_FULFILLED = 'GET_ORDERPENDING_FULFILLED'
export const GET_ORDERPENDING_REJECTED = 'GET_ORDERPENDING_REJECTED'

export const GET_ORDER_APPROVED = 'GET_ORDER_APPROVED'
export const GET_ORDER_APPROVED_FULFILLED = 'GET_ORDER_APPROVED_FULFILLED'
export const GET_ORDER_APPROVED_REJECTED = 'GET_ORDER_APPROVED_REJECTED'

export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_FULFILLED = 'GET_PROFILE_FULFILLED'
export const GET_PROFILE_REJECTED = 'GET_PROFILE_REJECTED'

export const LOGIN = 'LOGIN'
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED'
export const LOGIN_REJECTED = 'LOGIN_REJECTED'

// export const API = 'https://dumbtick-restapi.herokuapp.com/api/v1'
export const API = 'http://localhost:5000/api/v1'